// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs_login.proto

/*
Package pbcpl is a generated protocol buffer package.

It is generated from these files:
	cs_login.proto

It has these top-level messages:
	CSLogin
*/
package pbcpl

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 消息ID
type PACKET_ID int32

const (
	PACKET_ID_PACKET_CS_ERROR_SCError PACKET_ID = 0
	PACKET_ID_PACKET_CS_LOGIN_CSLogin PACKET_ID = 1
)

var PACKET_ID_name = map[int32]string{
	0: "PACKET_CS_ERROR_SCError",
	1: "PACKET_CS_LOGIN_CSLogin",
}
var PACKET_ID_value = map[string]int32{
	"PACKET_CS_ERROR_SCError": 0,
	"PACKET_CS_LOGIN_CSLogin": 1,
}

func (x PACKET_ID) Enum() *PACKET_ID {
	p := new(PACKET_ID)
	*p = x
	return p
}
func (x PACKET_ID) String() string {
	return proto.EnumName(PACKET_ID_name, int32(x))
}
func (x *PACKET_ID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PACKET_ID_value, data, "PACKET_ID")
	if err != nil {
		return err
	}
	*x = PACKET_ID(value)
	return nil
}
func (PACKET_ID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CSLogin struct {
	Cmd              *PACKET_ID `protobuf:"varint,1,opt,name=cmd,enum=PACKET_ID,def=1" json:"cmd,omitempty"`
	AccountName      *string    `protobuf:"bytes,2,req,name=accountName" json:"accountName,omitempty"`
	Password         *string    `protobuf:"bytes,3,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *CSLogin) Reset()                    { *m = CSLogin{} }
func (m *CSLogin) String() string            { return proto.CompactTextString(m) }
func (*CSLogin) ProtoMessage()               {}
func (*CSLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_CSLogin_Cmd PACKET_ID = PACKET_ID_PACKET_CS_LOGIN_CSLogin

func (m *CSLogin) GetCmd() PACKET_ID {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return Default_CSLogin_Cmd
}

func (m *CSLogin) GetAccountName() string {
	if m != nil && m.AccountName != nil {
		return *m.AccountName
	}
	return ""
}

func (m *CSLogin) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*CSLogin)(nil), "CSLogin")
	proto.RegisterEnum("PACKET_ID", PACKET_ID_name, PACKET_ID_value)
}

func init() { proto.RegisterFile("cs_login.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x2e, 0x8e, 0xcf,
	0xc9, 0x4f, 0xcf, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xaa, 0xe3, 0x62, 0x77, 0x0e,
	0xf6, 0x01, 0x09, 0x08, 0x99, 0x72, 0x31, 0x27, 0xe7, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xf0,
	0x19, 0x71, 0xe9, 0x05, 0x38, 0x3a, 0x7b, 0xbb, 0x86, 0xc4, 0x7b, 0xba, 0x58, 0x89, 0x43, 0x99,
	0xce, 0xc1, 0xf1, 0x3e, 0xfe, 0xee, 0x9e, 0x7e, 0xf1, 0x50, 0x1d, 0x41, 0x20, 0xf5, 0x42, 0x0a,
	0x5c, 0xdc, 0x89, 0xc9, 0xc9, 0xf9, 0xa5, 0x79, 0x25, 0x7e, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x0a,
	0x4c, 0x1a, 0x9c, 0x41, 0xc8, 0x42, 0x42, 0x52, 0x5c, 0x1c, 0x05, 0x89, 0xc5, 0xc5, 0xe5, 0xf9,
	0x45, 0x29, 0x12, 0xcc, 0x60, 0x69, 0x38, 0x5f, 0xcb, 0x95, 0x8b, 0x13, 0x6e, 0x91, 0x90, 0x34,
	0x17, 0x92, 0x55, 0xae, 0x41, 0x41, 0xfe, 0x41, 0xf1, 0xc1, 0xce, 0xae, 0x45, 0x45, 0xf9, 0x45,
	0x02, 0x0c, 0xa8, 0x92, 0x28, 0xee, 0x10, 0x60, 0x74, 0x62, 0x8f, 0x62, 0x2d, 0x48, 0x4a, 0x2e,
	0xc8, 0x01, 0x04, 0x00, 0x00, 0xff, 0xff, 0x5d, 0xf5, 0x12, 0xf9, 0xe0, 0x00, 0x00, 0x00,
}
